import * as XLSX from 'xlsx';
const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const money=v=>{if(typeof v==='number')return v;let s=String(v??'').replace(/R\$/gi,'').replace(/\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s.replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
const iso=v=>{if(v instanceof Date&&!isNaN(v))return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''}const s=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''};
const category=d=>{const t=norm(d),rules=[['Alimentação',['assai','ataca','mercado','mcdon','ifood','resta','lanch','padoc']],['Transporte',['uber','posto','sem parar','guiche']],['Saúde',['droga','raia','farma','total pass','vet']],['Assinaturas',['claro','desktop','apple','kiwify','stripe']],['Compras',['cea','lojas','havan','zara','shpp']],['Reserva',['cofrinho','aplicacao','resgate cdb']],['Tarifas/Juros',['iof','juros','adiant.depositante']],['Seguros',['seguro']],['Veículo/Impostos',['ipva','licenciamento']],['Salário',['salario','remuneracao']],['Transferências',['pix transf','ted']]];return rules.find(([,a])=>a.some(x=>t.includes(x)))?.[0]||'Outros'};
const neutral=d=>/cofrinho|resgate cdb|aplicacao|pix transf leonard/i.test(norm(d));
const clean=d=>String(d||'').replace(/\s*\d{2}\/\d{2}\s*$/,'').trim();
function common(d,a,ctx,id){const n=money(a),description=clean(d);return{household_id:ctx.householdId,user_id:ctx.userId,account_id:ctx.accountId,owner_profile_id:ctx.ownerId,transaction_date:id.date,description,amount:Math.abs(n),type:n>=0?'income':'expense',category:category(description),comment:neutral(description)?'Transferência neutra identificada na importação':'',is_neutral:neutral(description),import_hash:id.hash||`${ctx.accountId}|${id.date}|${norm(description)}|${n.toFixed(2)}|${id.index}`}}
export async function parseStatement(file,ctx){const ext=file.name.toLowerCase().split('.').pop();if(['xls','xlsx'].includes(ext))return parseItau(await file.arrayBuffer(),ctx);if(ext==='csv')return parseCsv(await file.text(),ctx);throw Error('Formato não suportado. Envie XLS, XLSX ou CSV.');}
function parseItau(buffer,ctx){const wb=XLSX.read(buffer,{type:'array',cellDates:true}),ws=wb.Sheets['Lançamentos']||wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true});let h=rows.findIndex(r=>norm(r[0])==='data'&&norm(r[1]).includes('lancamento'));if(h<0)throw Error('Não encontrei a seção de lançamentos do Itaú.');const out=[];for(let i=h+1;i<rows.length;i++){const r=rows[i],date=iso(r[0]),description=String(r[1]||'').trim(),amount=money(r[3]);if(!date||!description||!amount)continue;if(/saldo total disponivel dia|saldo anterior/i.test(norm(description)))continue;out.push(common(description,amount,ctx,{date,index:i}));}if(!out.length)throw Error('Nenhuma movimentação válida encontrada no XLS do Itaú.');return out;}
function parseCsv(text,ctx){const lines=text.replace(/^\uFEFF/,'').replaceAll('\r','').split('\n').filter(x=>x.trim()),sep=lines[0].includes(';')?';':',';const split=l=>{let q=false,c='',o=[];for(let i=0;i<l.length;i++){const x=l[i];if(x==='"'&&l[i+1]==='"'){c+='"';i++;}else if(x==='"')q=!q;else if(x===sep&&!q){o.push(c.trim());c='';}else c+=x}o.push(c.trim());return o};const h=split(lines[0]).map(norm),find=names=>h.findIndex(x=>names.some(n=>x===n||x.includes(n))),di=find(['data contabilizacao','data']),xi=find(['descricao','historico','lancamento']),oi=find(['valor original']),vi=oi>=0?oi:find(['valor','amount']),ii=find(['id importacao']),ci=find(['categoria sugerida']),ti=find(['transferencia neutra']);if(di<0||xi<0||vi<0)throw Error('CSV precisa conter Data, Descrição e Valor.');return lines.slice(1).map((l,i)=>{const r=split(l),date=iso(r[di]),n=money(r[vi]);if(!date||!n)return null;const row=common(r[xi],n,ctx,{date,index:i,hash:ii>=0?r[ii]:''});if(ci>=0&&r[ci])row.category=r[ci];if(ti>=0)row.is_neutral=/sim/i.test(r[ti]);return row}).filter(Boolean)}
