begin;
create extension if not exists pgcrypto;
create table public.households(id uuid primary key default gen_random_uuid(),name text not null,created_by uuid not null references auth.users(id),created_at timestamptz default now());
create table public.household_members(household_id uuid references public.households(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text default 'member',primary key(household_id,user_id));
create table public.profiles(id uuid primary key default gen_random_uuid(),household_id uuid references public.households(id) on delete cascade,user_id uuid references auth.users(id),name text not null);
create table public.accounts(id uuid primary key default gen_random_uuid(),household_id uuid references public.households(id) on delete cascade,owner_profile_id uuid references public.profiles(id),name text not null,type text default 'checking');
create table public.transactions(id uuid primary key default gen_random_uuid(),household_id uuid references public.households(id) on delete cascade,user_id uuid references auth.users(id),account_id uuid references public.accounts(id),owner_profile_id uuid references public.profiles(id),transaction_date date not null,description text not null,amount numeric(14,2) check(amount>0),type text check(type in('income','expense')),category text default 'Outros',comment text default '',import_hash text,created_at timestamptz default now());
create unique index transactions_import_unique on public.transactions(household_id,import_hash) where import_hash is not null;
create function public.is_member(hid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.household_members where household_id=hid and user_id=auth.uid())$$;
alter table public.households enable row level security;alter table public.household_members enable row level security;alter table public.profiles enable row level security;alter table public.accounts enable row level security;alter table public.transactions enable row level security;
create policy hh_select on public.households for select to authenticated using(public.is_member(id));
create policy hh_insert on public.households for insert to authenticated with check(created_by=auth.uid());
create policy hm_select on public.household_members for select to authenticated using(public.is_member(household_id));
create policy hm_insert on public.household_members for insert to authenticated with check(user_id=auth.uid());
create policy profiles_all on public.profiles for all to authenticated using(public.is_member(household_id)) with check(public.is_member(household_id));
create policy accounts_all on public.accounts for all to authenticated using(public.is_member(household_id)) with check(public.is_member(household_id));
create policy transactions_all on public.transactions for all to authenticated using(public.is_member(household_id)) with check(public.is_member(household_id) and user_id=auth.uid());
create function public.bootstrap_contas_casal() returns uuid language plpgsql security definer set search_path=public as $$declare hid uuid;leo uuid;reb uuid;begin select household_id into hid from public.household_members where user_id=auth.uid() limit 1;if hid is not null then return hid;end if;insert into public.households(name,created_by) values('Leonardo e Rebeca',auth.uid()) returning id into hid;insert into public.household_members values(hid,auth.uid(),'owner');insert into public.profiles(household_id,user_id,name) values(hid,auth.uid(),'Leonardo') returning id into leo;insert into public.profiles(household_id,name) values(hid,'Rebeca') returning id into reb;insert into public.accounts(household_id,owner_profile_id,name) values(hid,leo,'Conta principal Leonardo'),(hid,reb,'Conta principal Rebeca');return hid;end$$;
grant execute on function public.bootstrap_contas_casal() to authenticated;
commit;
